# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json

language: ja-JP
tone_instructions: "可能な限りわかりやすく解説してください。"
early_access: false
enable_free_tier: true
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: ""
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: true
  suggested_reviewers: true
  auto_assign_reviewers: false
  poem: false
  labeling_instructions:
    - label: "bug"
      instructions: "バグ対応"
    - label: "refactor"
      instructions: "リファクタ"
    - label: "fix"
      instructions: "修正"
    - label: "update"
      instructions: "更新"
    - label: "new"
      instructions: "新規機能"
  path_filters: []
  path_instructions:
    - path: "**/*.{js,ts,vue}"
      instructions: |
        - 変数、関数名はlowerCamelCase(ファイル名含む)
        - クラス名はupperCamelCase(ファイル名含む)
        - var禁止
        - 再代入の無いlet宣言は禁止
        - 同じ処理は反復処理化や関数化する
        - マジックナンバーは禁止。定数化する
        - 理解しにくい処理はコメントを適宜追加する
        - function内でfunctionの宣言は禁止
        - ネストを深くしすぎない
        - エラーハンドリングは呼び出し元で行う
    - path: "**/*.{html,vue}"
      instructions: |
        - htmlファイル名はlowerCamelCase
        - クラス名はkebab-case
        - クラス名は2階層までを推奨。2単語を1つの塊として扱う場合は2単語をlowerCamelCaseで繋げる
        - 状態を表すクラス名はアンダーバー始まり
        - SEOを意識
        - アクセシビリティ対応を意識
    - path: "**/*.{css,vue}"
      instructions: |
        - フォントサイズはremで行う
        - cssファイル名はlowerCamelCase
        - 要素の外側への余白設定は左 or 上に設定する
        - paddingとmarginを明確に使い分ける
        - コンポーネント化したスタイルは外部に影響のあるスタイルは原則禁止
    - path: "**/*.vue"
      instructions: |
        - vueファイル名はupperCamelCase
        - ルートの要素のクラス名はコンポーネント名と同一にする
        - 1つのコンポーネントが持つ役割をできるだけ小さくする
        - 共通的なコンポーネントは再利用しやすい記述をする
        - 複雑なロジックや繰り返し使う処理は切り分ける
        - 処理を切り分ける際にアプリ全体で利用する場合はstore、コンポーネント単位で完結できる場合はcomposableを利用
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches: ["^dev.*$", "^stg.*$", "^main.*$", "^release.*$"]
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
  tools:
    ast-grep:
      rule_dirs: []
      util_dirs: []
      essential_rules: true
      packages: []
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      enabled_only: false
      level: default
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
      config_file: ""
    phpstan:
      enabled: true
      level: default
    golangci-lint:
      enabled: true
      config_file: ""
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: true
      config_file: ""
    eslint:
      enabled: true
    flake8:
      enabled: true
    rubocop:
      enabled: true
    buf:
      enabled: true
    regal:
      enabled: true
    actionlint:
      enabled: true
    pmd:
      enabled: true
      config_file: ""
    phpmd:
      enabled: true
    phpcs:
      enabled: true
    cppcheck:
      enabled: true
    semgrep:
      enabled: true
      config_file: ""
    circleci:
      enabled: true
    clippy:
      enabled: true
    sqlfluff:
      enabled: true
    prismaLint:
      enabled: true
    pylint:
      enabled: true
    oxc:
      enabled: true
    shopifyThemeCheck:
      enabled: true
    luacheck:
      enabled: true
    brakeman:
      enabled: true
    dotenvLint:
      enabled: true
    htmlhint:
      enabled: true
    checkmake:
      enabled: true
chat:
  auto_reply: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: auto
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns: []
  learnings:
    scope: auto
  issues:
    scope: local
  jira:
    usage: disabled
    project_keys: []
  linear:
    usage: auto
    team_keys: []
  pull_requests:
    scope: local
code_generation:
  docstrings:
    language: ja-JP
    path_instructions:
      - path: ""
        instructions: ""
  unit_tests:
    path_instructions:
      - path: ""
        instructions: ""
